Repository pda-min-ji/back, pull requests merged in 2024-11, with the labels that each got.

#5 ranking테이블 생성
  src/main/java/king_min_ji_server/demo/domain/Ranking.java
  src/main/java/king_min_ji_server/demo/domain/User.java
Labels: :memo: documentation

#7 #6 Feat : 코테문제 DB 주입 기능
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/king_min_ji_server/.DS_Store
  src/main/java/king_min_ji_server/demo/ServerApplication.java
  src/main/java/king_min_ji_server/demo/domain/Question.java
  src/main/java/king_min_ji_server/demo/domain/Tag.java
  src/main/java/king_min_ji_server/demo/domain/mapping/Question_Tag.java
  src/main/java/king_min_ji_server/demo/repostiory/QuestionRepository.java
  src/main/java/king_min_ji_server/demo/repostiory/QuestionTagRepository.java
  src/main/java/king_min_ji_server/demo/repostiory/TagRepository.java
  src/main/java/king_min_ji_server/demo/service/QuestionService.java
  src/main/resources/application.yml
  src/main/resources/questionData/output.json
  src/test/java/king_min_ji_server/demo/service/QuestionServiceTest.java
Labels: :sparkles: Feature

#9 #8 Feat : 오늘의 문제 무작위로 3개 조회
  src/main/java/king_min_ji_server/demo/converter/QuestionConverter.java
  src/main/java/king_min_ji_server/demo/domain/Question.java
  src/main/java/king_min_ji_server/demo/repostiory/QuestionRepository.java
  src/main/java/king_min_ji_server/demo/repostiory/QuestionTagRepository.java
  src/main/java/king_min_ji_server/demo/service/QuestionService.java
  src/main/java/king_min_ji_server/demo/web/controller/QuestionController.java
  src/main/java/king_min_ji_server/demo/web/dto/QuestionResponse.java
  src/main/resources/application.yml
  src/test/java/king_min_ji_server/demo/service/QuestionServiceTest.java
Labels: :sparkles: Feature

#14 #12 Feat : 유저 프로필(정보) 조회
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
  src/main/java/king_min_ji_server/demo/converter/QuestionConverter.java
  src/main/java/king_min_ji_server/demo/converter/UserConverter.java
  src/main/java/king_min_ji_server/demo/domain/User.java
  src/main/java/king_min_ji_server/demo/repository/QuestionRepository.java
  src/main/java/king_min_ji_server/demo/repository/QuestionTagRepository.java
  src/main/java/king_min_ji_server/demo/repository/TagRepository.java
  src/main/java/king_min_ji_server/demo/repository/TestRepository.java
  src/main/java/king_min_ji_server/demo/repository/UserRepository.java
  src/main/java/king_min_ji_server/demo/repostiory/TestRepository.java
  src/main/java/king_min_ji_server/demo/service/QuestionService.java
  src/main/java/king_min_ji_server/demo/service/UserService.java
  src/main/java/king_min_ji_server/demo/web/controller/UserController.java
  src/main/java/king_min_ji_server/demo/web/dto/ProfileResponse.java
  src/main/resources/application.yml
  src/test/java/king_min_ji_server/demo/service/QuestionServiceTest.java
Labels: :sparkles: Feature

#17 UserService import 오류 해결
  src/main/java/king_min_ji_server/demo/service/UserService.java
Labels: :bug: Debug

#19 랭킹 조회API
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
  src/main/java/king_min_ji_server/demo/converter/Total_rankingConverter.java
  src/main/java/king_min_ji_server/demo/converter/Week_rankingConverter.java
  src/main/java/king_min_ji_server/demo/domain/Total_ranking.java
  src/main/java/king_min_ji_server/demo/domain/User.java
  src/main/java/king_min_ji_server/demo/domain/Week_ranking.java
  src/main/java/king_min_ji_server/demo/repository/TotalRankingRepository.java
  src/main/java/king_min_ji_server/demo/repository/WeekRankingRepository.java
  src/main/java/king_min_ji_server/demo/service/TotalRankService.java
  src/main/java/king_min_ji_server/demo/service/WeekRankService.java
  src/main/java/king_min_ji_server/demo/web/controller/RankController.java
  src/main/java/king_min_ji_server/demo/web/dto/RankResponseDTO.java
  src/test/java/king_min_ji_server/demo/RankControllerTest.java
  src/test/java/king_min_ji_server/demo/controller/RankControllerTest.java
  src/test/java/king_min_ji_server/demo/service/TotalRankServiceTest.java
  src/test/java/king_min_ji_server/demo/service/WeekRankServiceTest.java
Labels: :sparkles: Feature

#24 #10 Fix : 충돌 해결
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
Labels: :memo: documentation, :recycle: Refactoring, :sparkles: Feature

#25 #23 Fix : 의존성 주입 문제 해결
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
  src/main/java/king_min_ji_server/demo/config/WebConfig.java
  src/main/resources/application.yml
  src/test/java/king_min_ji_server/demo/ResetWeekRankingJobTest.java
Labels: :recycle: Refactoring

#26 #23 Fix : 오타 수정
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
Labels: :recycle: Refactoring

#29 #28 Fix : modify cors & questions/correct
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
  src/main/java/king_min_ji_server/demo/web/dto/CorrectRequest.java
  src/main/resources/application.yml
Labels: :bug: Debug

#30 #27 Feat : 모든 사용자의 점수 조회
  src/crawling/node_modules/.bin/browsers 2
  src/crawling/node_modules/.bin/escodegen 2
  src/crawling/node_modules/.bin/esgenerate 2
  src/crawling/node_modules/.bin/esparse 2
  src/crawling/node_modules/.bin/esvalidate 2
  src/crawling/node_modules/.bin/extract-zip 2
  src/crawling/node_modules/.bin/js-yaml 2
  src/crawling/node_modules/.bin/puppeteer 2
  src/crawling/node_modules/.bin/rimraf 2
  src/crawling/node_modules/.bin/semver 2
  src/main/java/king_min_ji_server/demo/config/SecurityConfig.java
  src/main/java/king_min_ji_server/demo/repository/UserQuestionRepository.java
  src/main/java/king_min_ji_server/demo/service/QuestionService.java
  src/main/java/king_min_ji_server/demo/web/controller/QuestionController.java
  src/main/java/king_min_ji_server/demo/web/dto/TotalPointResponse.java
  src/test/java/king_min_ji_server/demo/service/QuestionServiceTest.java
Labels: :sparkles: Feature

#33 #32 Fix : 사용자가 푼 문제를 Ranking 테이블에도 저장하도록 변경
  src/crawling/node_modules/.bin/browsers 3
  src/crawling/node_modules/.bin/escodegen 3
  src/crawling/node_modules/.bin/esgenerate 3
  src/crawling/node_modules/.bin/esparse 3
  src/crawling/node_modules/.bin/esvalidate 3
  src/crawling/node_modules/.bin/extract-zip 3
  src/crawling/node_modules/.bin/js-yaml 3
  src/crawling/node_modules/.bin/puppeteer 3
  src/crawling/node_modules/.bin/rimraf 3
  src/crawling/node_modules/.bin/semver 3
  src/main/java/king_min_ji_server/demo/repository/TotalRankingRepository.java
  src/main/java/king_min_ji_server/demo/repository/WeekRankingRepository.java
  src/main/java/king_min_ji_server/demo/service/QuestionService.java
  src/main/java/king_min_ji_server/demo/service/TotalRankService.java
  src/main/java/king_min_ji_server/demo/service/WeekRankService.java
  src/main/resources/application.yml
Labels: :recycle: Refactoring

#37 #36 Fix : modify user login response DTO & logic
  src/main/java/king_min_ji_server/demo/converter/UserConverter.java
  src/main/java/king_min_ji_server/demo/service/UserService.java
  src/main/java/king_min_ji_server/demo/web/controller/UserController.java
  src/main/java/king_min_ji_server/demo/web/dto/UserProfileResponseDto.java
Labels: :recycle: Refactoring
